stages:
  - build

build:regular:
  stage: build
  image: alex7r/lamp:ccp
  script:
    - if grep -rn './' -e "\xEF\xBB\xBF"; then exit 1; fi
    - grep -E -o '<version>(.*?)</version>' ./pkg_html5flippingbook.xml | sed -E 's/<version>|<\/version>//g' | while read version; do find ./com_html5flippingbook/admin/sql/updates/ -maxdepth 2 -name "*.sql" -print |  sed -E 's/.*\/|\.sql//g' | while read sqin; do if [ "$sqin" \> "$version" ]; then exit 1; fi; done; done
# delete updater temporary
    - sed -E -i 's/<file.*?_joomplaceupdater.zip<\/file>//g' ./pkg_html5flippingbook.xml
    - mkdir packages
    - | \
      grep -E -o '<file.*>(.*?)</file>' ./pkg_html5flippingbook.xml \
      | \
      sed -r 's/<file.*?src="([^"]*?)".*?>.*.zip<\/file>|<file.*?>(.*).zip<\/file>/\1\2/' \
      | \
      while read in; \
      do \
        if \[ "$in" != 'plg_installer_joomplaceupdater' \]; \
          then \
            if \[\[ $in =~ ^https?: \]\]; \
              then \
                cd ./../packages/; \
                wget "$in"; \
              else \
                cd ./"$in"; \
                zip -r ./../packages/"$in".zip ./*; \
                cd ./../; \
            fi; \
        fi; \
      done
  artifacts:
    paths:
    - packages/
    - pkg_html5flippingbook.xml
    name: "pkg_html5flippingbook_${CI_BUILD_REF_NAME}"
    when: on_success
    expire_in: 10 minutes
#
#build:pro:
#  stage: build
#  image: alex7r/lamp:ccp
#  before_script:
#    - zip -v
#  script:
#    - if grep -rn './' -e "\xEF\xBB\xBF"; then exit 1; fi
#    - grep -E -o '<version>(.*?)</version>' ./pkg_html5flippingbook_pro.xml | sed -E 's/<version>|<\/version>//g' | while read version; do find ./com_html5flippingbook_pro/admin/sql/updates/ -maxdepth 2 -name "*.sql" -print |  sed -E 's/.*\/|\.sql//g' | while read sqin; do if [ "$sqin" \> "$version" ]; then exit 1; fi; done; done
## delete updater temporary
#    - sed -E -i 's/<file.*?_joomplaceupdater.zip<\/file>//g' ./pkg_html5flippingbook_pro.xml
#    - mkdir packages
#    - grep -E -o '<file.*>(.*?)</file>' ./pkg_html5flippingbook_pro.xml |  sed -E 's/<file[^>]+>|.zip<\/file>//g' | while read in; do if [ "$in" != 'plg_installer_joomplaceupdater' ]; then cd ./"$in"; zip -r ./../packages/"$in".zip ./*; cd ./../; fi; done
#    - pwd
#  artifacts:
#    paths:
#    - packages/
#    - pkg_html5flippingbook_pro.xml
#    name: "pkg_html5flippingbook_pro_${CI_BUILD_REF_NAME}"
#    when: on_success
#    expire_in: 1 day